const axios = require('axios');
const mumaker = require('mumaker');

// Forwarded branding info
const channelInfo = {
    forwardingScore: 1,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363281985436737@newsletter',
        newsletterName: 'Minato-MD',
        serverMessageId: -1
    }
};

// Message format templates
const messageTemplates = {
    error: (msg) => ({ text: msg, contextInfo: channelInfo }),
    success: (caption, imageUrl) => ({
        image: { url: imageUrl },
        caption: `🌟 *${caption}*\nGenerated by Minato-MD`,
        contextInfo: channelInfo
    })
};

// Map of all supported styles
const ephotoURLs = {
    metallic: "https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html",
    ice: "https://en.ephoto360.com/ice-text-effect-online-101.html",
    snow: "https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html",
    impressive: "https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html",
    matrix: "https://en.ephoto360.com/matrix-text-effect-154.html",
    light: "https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html",
    neon: "https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html",
    devil: "https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html",
    purple: "https://en.ephoto360.com/purple-text-effect-online-100.html",
    thunder: "https://en.ephoto360.com/thunder-text-effect-online-97.html",
    leaves: "https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html",
    '1917': "https://en.ephoto360.com/1917-style-text-effect-523.html",
    arena: "https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html",
    hacker: "https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html",
    sand: "https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html",
    blackpink: "https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html",
    glitch: "https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html",
    fire: "https://en.ephoto360.com/flame-lettering-effect-372.html"
};

async function textmakerCommand(sock, chatId, message, q, type) {
    try {
        if (!q) {
            return await sock.sendMessage(chatId, messageTemplates.error(`❌ Please provide text\nExample: *.${type} Talha*`));
        }

        const text = q.trim();
        const style = type.toLowerCase();
        const url = ephotoURLs[style];

        if (!url) {
            return await sock.sendMessage(chatId, messageTemplates.error(`❌ Invalid style: *${type}*\nUse a valid one like: metallic, fire, hacker, neon, etc.`));
        }

        const result = await mumaker.ephoto(url, text);

        if (!result?.image) {
            throw new Error("Image generation failed.");
        }

        await sock.sendMessage(chatId, messageTemplates.success(text, result.image));
        
    } catch (error) {
        console.error(`Error in textmaker [${type}]:`, error);
        await sock.sendMessage(chatId, messageTemplates.error(`❌ Failed to generate image.\n🔧 Error: ${error.message}`));
    }
}

module.exports = textmakerCommand;
          
